name: Build Heart Sayings Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: curatimeXai
          
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build image
        run: |
          docker build \
            -t ghcr.io/curatimexai/heart-sayings:${{ github.sha }} \
            -t ghcr.io/curatimexai/heart-sayings:latest \
            ./backend

      - name: Push image
        run: |
          docker push ghcr.io/curatimexai/heart-sayings:${{ github.sha }}
          docker push ghcr.io/curatimexai/heart-sayings:latest